[project]
name = "calculate-pi"
version = "0.5.0"
description = "Calculate Pi python poetry project demo"
authors = [{ name = "Erik Ferlanti", email = "eferlanti@tacc.utexas.edu" }]
requires-python = "~=3.12.0"
readme = "README.md"
license = "BSD-3-Clause"
dependencies = [
    "click>=8.1.7,<9",
    "click-loglevel>=0.6.1",
]

[project.urls]
Repository = "https://github.com/eriksf/calculate-pi"

[project.scripts]
calculate-pi = "calculate_pi.pi:main"

[dependency-groups]
dev = [
    "pytest>=8.3.2,<9",
    "pytest-cov>=6.2.1",
    "ruff>=0.12.8",
]

[tool.hatch.build.targets.sdist]
include = ["calculate_pi"]

[tool.hatch.build.targets.wheel]
include = ["calculate_pi"]


[tool.bumpversion]
current_version = "0.5.0"
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)"
serialize = ["{major}.{minor}.{patch}"]
search = "{current_version}"
replace = "{new_version}"
regex = false
ignore_missing_version = false
ignore_missing_files = false
tag = false
sign_tags = false
tag_name = "v{new_version}"
tag_message = "Bump version: {current_version} → {new_version}"
allow_dirty = true
commit = false
message = "Bump version: {current_version} → {new_version}"
moveable_tags = []
commit_args = ""
setup_hooks = []
pre_commit_hooks = []
post_commit_hooks = []

[[tool.bumpversion.files]]
filename = "calculate_pi/version.py"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff]
exclude = [".git", ".ruff_cache", ".vscode"]
line-length = 300

[tool.ruff.lint]
select = ["E", "F", "I"]
fixable = ["ALL"]
unfixable = ["F401"]

[tool.pytest.ini_options]
addopts = "--verbose --cov=calculate_pi"

