name: Python unit test

on:
    push:
    workflow_dispatch:

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.9"
          enable-cache: true
          cache-dependency-glob: "**/pyproject.toml"

      - name: Minimize uv cache
        run: uv cache prune --ci

      - name: Install project
        run: uv sync --frozen --all-extras --dev

      - name: Test with pytest
        run: uv run pytest --cov=calculate_pi
